FROM node:16-alpine
RUN apk --no-cache add git
WORKDIR /app
COPY ./server/server.js   ./server.js
COPY ./server/package.json ./package.json
RUN npm install --only=production

CMD ["sh", "-c", "node server.js"]